### ISSUE TITLE
setup: Support  2-factor authentication

### ISSUE THREAD

**Issue by brianmay** [sociomantic-tsunami/git-hub#107]
# Issue

```
$ ./git-hub setup --global --user brianmay
GitHub password (will not be stored): 
Looking for GitHub authorization tokens...
Error: GitHub error: Must specify two-factor authentication OTP code.
```

There doesn't seem to be anyway that I can see for providing the OTP code.

---

# Quick workaround

1. Create a personal access token: https://github.com/settings/tokens/new
2. Use `git-hub` as the name (or whatever you like) and mark the `user` and `repo` scopes and "Generate" the token.
   
   ![Personal Access Token Form](https://cloud.githubusercontent.com/assets/2684688/17331374/e09f39c2-58ca-11e6-97e8-fc408dc4671b.png)
3. Copy the new token hash.
   
   ![Token Hash](https://cloud.githubusercontent.com/assets/2684688/17331172/15d57fb2-58ca-11e6-8698-a7ed1267912d.png)
4. Type in a console:
   
   ```
   git config --global hub.username <username>`
   git config --global hub.oauthtoken <token>`
   ```
   
   Where `<username>` is your GitHub username and `<token>` is the new generated token hash. Using `--global` will make this your default global credentials for GitHub, if you want to set it up in a per project basis, don't use `--global`.

Done! After these steps you won't need to use the `setup` command anymore.

**Comment by leandro-lucarella-sociomantic** [comment]
Related documentation: https://developer.github.com/v3/auth/#working-with-two-factor-authentication

For now the workaround is to go and created the OAuth token manually.

**Comment by leandro-lucarella-sociomantic** [comment]
Updated issue description with a detailed step-by-step workaround.

**Comment by jakubpawlowicz** [comment]
+1

**Comment by cg2v** [comment]
Passwords are going to stop working for everyone: https://developer.github.com/changes/2020-02-14-deprecating-password-auth/

The API you use to get an oauth token is also going away: https://developer.github.com/changes/2020-02-14-deprecating-oauth-auth-endpoint/; Even now, I can't use a personal access token with it:

cg2v@MAYA:~/Autolab$ git hub setup
Using Git repository local configuration
GitHub username [cg2v]:
GitHub password (will not be stored): <a personal access token with repo and user rights>
Looking for GitHub authorization token...
Error: GitHub error: This API can only be accessed with username and password Basic Auth

**Comment by llucax** [comment]
This is not good but it's a different issue, can you please create a new one?

The workaround mentioned here still works, right?

**Comment by cg2v** [comment]
It does work, I didn't read the workaround carefully. I assumed the token was used as a password (since that's what I had to do for a mobile app)

**Comment by llucax** [comment]
Thanks for checking. Is an awful issue, but since there is an easy workaround and is a one-time-only setup thing, is in a very low priority for me, so I don't think I will address it unless I find myself with a lot of free time and nothing better to do, of which there is a high probability that will never happen :)

If someone else want to tackle it, I'll be very happy to merge it!

**Comment by llucax** [comment]
I changed the type to bug (as if passwords are going away, this will be broken for everyone, so we might as well just require users to bring their own token always) and assigned low prio because of the reasons stated above.

**Comment by llucax** [comment]
I changed the priority to high. Even when there is an easy workaround, this gives a very **very** bad impression to new users, to the point where users can just move away from the tool thinking that it is completely broken (with good reason if the first step you need to do to use it gives you and unrecoverable error).

**Comment by llucax** [comment]
On a second look, this issue can't be fixed now, as GitHub completely ditched basic auth (with or without 2FA), so there is no way to access GitHub API now that it's not with a per-existing GitHub PAT (Personal Access Token).

I will close this issue as `wontfix` and reopen #288.
