### ISSUE TITLE
Comment replies are not shown together

### ISSUE THREAD

**Issue by NightTsarina** [sociomantic-tsunami/git-hub#109]
When using git hub pull show, I get all the comments, which is a great feature, but the replies are not shown together or nested, which makes it difficult to follow the conversation.

**Comment by leandro-lucarella-sociomantic** [comment]
I just realized this issue referred to pull request review comments, which can be grouped. And this issue was actually fixed by e8d946f5ef9f2ee72ef0f36317cb49ee7b7eafee.
