### ISSUE TITLE
Link commits to their PR

### ISSUE THREAD

**Issue by mathias-lang-sociomantic** [sociomantic-tsunami/git-hub#155]
One of the annoying drawback of the rebase-the-pull-requests approach is the impossibility to link a commit to a P.R. and then, its discussions.

One of the approach we could take would be to append, `Part of org/repo#id` if none of `Fix`, `Fixes`, `Part of` is already present.

**Comment by mihails-strasuns-sociomantic** [comment]
Another option is to always append empty body commit message that links to PR on top of rebased PR commits, similar to merge commits (but with linear history).

**Comment by mihails-strasuns-sociomantic** [comment]
I will try implementing something as soon as @leandro-lucarella-sociomantic makes his dictator decision.

**Comment by leandro-lucarella-sociomantic** [comment]
To be honest, I don't like it. It is not enough to just mention the #issue in the commit message? That's a good practice anyway. My feeling is, doing any of those is way too intrusive, and if you **really really** need that information, then you probably are better by just using merges instead of rebase.

**Comment by mathias-lang-sociomantic** [comment]
> To be honest, I don't like it. It is not enough to just mention the #issue in the commit message? That's a good practice anyway. My feeling is, doing any of those is way too intrusive, and if you really really need that information, then you probably are better by just using merges instead of rebase.

It's not only about the issue, but the P.R. itself. It's often very informative to have the discussions available to gather more context.
I don't like it either TBH, as it's a hack, and I would really love for us to use merge, but that's not my call.

**Comment by leandro-lucarella-sociomantic** [comment]
> It's not only about the issue, but the P.R. itself. It's often very informative to have the discussions available to gather more context.

Shouldn't the PR and issue be always linked?

**Comment by mihails-strasuns-sociomantic** [comment]
> Shouldn't the PR and issue be always linked?

GitHub doesn't provide backlink to PR from the issue if they are separate, only to commit (which is rebased in `git-hub` case)

**Comment by mihails-strasuns-sociomantic** [comment]
I don't want to engage in longer discussion right now but want to clarify - Mathias actually wanted to go with plain merges originally but I dislike it and proposed referencing it with `git-hub` tool as alternative.

**Comment by leandro-lucarella-sociomantic** [comment]
What I mean, isn't it common to say "Fixes #NNN" in commits, which links ALL the commits (all the rebases versions of the commit) to the issue? Then if you didn't link the issue to the PR, we can't do magic. You can get sort of automatic linking if you attach code to the issue instead of creating a new PR, that way the issue becomes the PR and everybody is happy.

Am I missing something?

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, the topic is about automatically connecting rebased commits to the _pull request_, not the issue. If those are not the same, there is not quick way to go from "Fixes #XXX" (and thus XXX) to PR that originated that commit, unless someone did reference it manually (somewhat rare thing).

**Comment by leandro-lucarella-sociomantic** [comment]
So this would be only useful if you have an issue and a pull request that fixes that issue, but nobody ever mentioned the issue in the pull request or vice-versa, is that right?

**Comment by mihails-strasuns-sociomantic** [comment]
Yes. This may be is more common than you may think though.

**Comment by leandro-lucarella-sociomantic** [comment]
It still looks like a very ugly hack just to fix something that can be fixed by encouraging a more healthy linking between issues and PR that fixes them...

**Comment by mathias-lang-sociomantic** [comment]
> So this would be only useful if you have an issue and a pull request that fixes that issue, but nobody ever mentioned the issue in the pull request or vice-versa, is that right?

Or if there is no issue and just a P.R.

**Comment by leandro-lucarella-sociomantic** [comment]
> Or if there is no issue and just a P.R.

Good point.

**Comment by mathias-baumann-sociomantic** [comment]
Related: http://stackoverflow.com/questions/17818167/find-a-pull-request-on-github-where-a-commit-was-originally-created

**Comment by leandro-lucarella-sociomantic** [comment]
Problem solved? Close as wontfix? :)

**Comment by mathias-lang-sociomantic** [comment]
> Problem solved? Close as wontfix? :)

When you rebase, you change the commit sha. So @mathias-baumann-sociomantic is not applicable.

**Comment by leandro-lucarella-sociomantic** [comment]
But both the old and new commit hashes linked to the issue if you use the "fixes XXX" comment and in the PR (added as a comment by the tool).

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, only the last commit hash is mentioned in the comment, so maybe we just need to add all the rebased commits hashes in the comment?

**Comment by mathias-baumann-sociomantic** [comment]
Sounds dirty, but I don't see other ways

**Comment by mihails-strasuns-sociomantic** [comment]
.. or just link the issue/pr from the commit? What is dirtier?

**Comment by mathias-lang-sociomantic** [comment]
I'd favor linking the P.R. from every commit as well.

**Comment by leandro-lucarella-sociomantic** [comment]
Nope, I think touching commit messages from people is the dirtiest thing EVER. Over my dead body (or in git terms, over your fork! :P)

**Comment by gautam-kotian-sociomantic** [comment]
I wonder if we could use [git notes](https://www.kernel.org/pub/software/scm/git/docs/git-notes.html) for this.

**Comment by mihails-strasuns-sociomantic** [comment]
After totally forgetting this and being reminded I studied how git notes work. It looks very promising and totally matching our use case. Plain manual entry is not very clear but this article really explains the details: https://git-scm.com/blog/2010/08/25/notes.html

Short summary:
```
$ git notes add -m "PR #1034" HEAD
$ git log
Author: Mihails Strasuns <mihails.strasuns.contractor@sociomantic.com>
Date:   Wed Jan 13 14:40:39 2016 +0200

    Title

Notes:
    PR #1034
$ git push origin refs/notes/commits
```
In a different clone:
```
$ git fetch origin refs/notes/commits:refs/notes/commits
 * [new ref]         refs/notes/commits -> refs/notes/commits
```

Important features:
- git note storage is essentially a new git ref stored in separate namespace:
```
$ git show-ref
62c2d3da341f6a4c19a4e46586d70bcf8c2d597b refs/heads/master
35eafbdaaccd0f903c5fcf942d1aee7532dbfc54 refs/notes/commits
0ab7dc53eedd6951da58226554ef439d8436ceea refs/remotes/origin/HEAD
0ab7dc53eedd6951da58226554ef439d8436ceea refs/remotes/origin/master
$ git show 35eafbdaaccd0f903c5fcf942d1aee7532dbfc54
commit 35eafbdaaccd0f903c5fcf942d1aee7532dbfc54
Author: Mihails Strasuns <mihails.strasuns.contractor@sociomantic.com>
Date:   Wed Jan 13 14:41:23 2016 +0200

    Notes added by 'git notes add'

diff --git a/0ab7dc53eedd6951da58226554ef439d8436ceea b/0ab7dc53eedd6951da58226554ef439d8436ceea
new file mode 100644
index 0000000..2f9dba1
--- /dev/null
+++ b/0ab7dc53eedd6951da58226554ef439d8436ceea
@@ -0,0 +1 @@
+PR #1034
```
- it does not affect original commit in any way but presence of a note is checked by `git log`/`git show` when showing commit
- but for same reason connection is lost when you do `commit --amend` (or rebase) and hash changes. I haven't yet figured how to rebind the note in such case

Overall summary : git-hub can totally do such annotation automatically without affecting git history but it will need some care/research to avoid screwing the commit-note relation

**Comment by mihails-strasuns-sociomantic** [comment]
I have managed to copy/move the note after amending like this:

```
git notes copy OLD-HASH NEW-HASH
git notes remove OLD-HASH
````

Not very pretty but doable by git-hub if needed (and no one should rewrite already merged history anyway :P)

**Comment by mathias-baumann-sociomantic** [comment]
Hmm note reattaching got get ugly for rebases

**Comment by mathias-lang-sociomantic** [comment]
That's pretty much right on spot.
I don't think notes reattaching is an issue (famous last words ik), as once a commit make it into the blessed repo, it should not be rebased (it messes with other git features, like signing).

**Comment by mathias-baumann-sociomantic** [comment]
Well, if it's only done for the final merge/rebase then it's fine

**Comment by mihails-strasuns-sociomantic** [comment]
Yes, intention is that git-hub could add such notes when you do `git hub pull rebase PR-ID` and push them upstream as part of the command.

**Comment by leandro-lucarella-sociomantic** [comment]
It does looks promising indeed, now we just need someone that wants to give it a shot ;)

**Comment by mihails-strasuns-sociomantic** [comment]
If no one will take it during next month or two please remind me.

**Comment by mathias-lang-sociomantic** [comment]
*Reminds @mihails-strasuns-sociomantic *

**Comment by joseph-wakeling-sociomantic** [comment]
> My feeling is, doing any of those is way too intrusive, and if you really really need that information, then you probably are better by just using merges instead of rebase.

See sociomantic-tsunami/git-hub#154 ;-)

**Comment by mathias-lang-sociomantic** [comment]
*Reminds @mihails-strasuns-sociomantic *

**Comment by mathias-lang-sociomantic** [comment]
Since Github now allows us to do this, I rest my case.
