### ISSUE TITLE
fatal: Ambiguous object name: 'FETCH_HEAD'.

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/git-hub#179]
I accidentally created branch called `FETCH_HEAD`. After that it was impossible to do `git hub pull rebase <id>`:

```
Fetching <snip> from git@github.com:<snip>/<snip>.git
Error: git checkout --quiet -b git-hub-pull-rebase-<snip> FETCH_HEAD failed (return code: 128)
warning: refname 'FETCH_HEAD' is ambiguous.
warning: refname 'FETCH_HEAD' is ambiguous.
fatal: Ambiguous object name: 'FETCH_HEAD'.
```

**Comment by leandro-lucarella-sociomantic** [comment]
Mmm, that's almost as creating a branch called `HEAD`. I'm not sure there is much to do about it, is a git thing... I'm not sure if there is a way to disambiguate the reference, as it's stored directly in `.git/FETCH_HEAD` by [git fetch](https://www.kernel.org/pub/software/scm/git/docs/git-fetch.html).

I tried it locally and it works for `git show` but fails for `git checkout`. Git [documentation says](https://git-scm.com/docs/git-rev-parse#_specifying_revisions) that references in `.git/` should take precedence (if I understand correctly).

If there is a bug, I think it is in Git upstream, so I'll close as invalid. Feel free to reopen if you think this is wrong.
