### ISSUE TITLE
Error when creating pull request 

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic-tsunami/git-hub#211]
Trying to create a new pull request from a local branch using `git hub pull new -b <my-local-branch-name>`
The branch in my repo is created but the creation of new pull request against upstream returns the error 

> Error: GitHub error: Validation Failed
Error: HTTP Error 422: Unprocessable Entity
Error: https://api.github.com/repos/sociomantic-tsunami/libdrizzle-redux/pulls
Error: <httplib.HTTPMessage instance at 0x7ff8929a8ef0>
Error: {"message":"Validation Failed","errors":[{"resource":"PullRequest","field":"base","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/pulls/#create-a-pull-request"}

**Comment by leandro-lucarella-sociomantic** [comment]
This is usually related to trying to create a PR to the wrong repo, can you post a `git remote -v` and `git config --get-regexp hub.*` (**make sure to remove all authentication variables before posting!**).

**Comment by andreas-bok-sociomantic** [comment]
`remote -v` 
> origin	git@github.com:andreas-bok-sociomantic/libdrizzle-redux.git (fetch)
origin	git@github.com:andreas-bok-sociomantic/libdrizzle-redux.git (push)
upstream	git@github.com:sociomantic-tsunami/libdrizzle-redux.git (fetch)
upstream	git@github.com:sociomantic-tsunami/libdrizzle-redux.git (push

`git config --get-regexp hub.*`
> hub.username andreas-bok-sociomantic
hub.oauthtoken ********************************
hub.urltype ssh_url
hub.upstream sociomantic-tsunami/libdrizzle-redux

**Comment by jwilk** [comment]
> Trying to create a new pull request from a local branch using `git hub pull new -b <my-local-branch-name>`

The argument to `-b` is the *upstream* branch you want your changes pulled into, not your local branch.
You probably want this instead:

    git hub pull new <my-local-branch-name>

**Comment by andreas-bok-sociomantic** [comment]
> The argument to -b is the upstream branch you want your changes pulled into, not your local branch.
You probably want this instead:

Yes, solves the issue. Tx. I will close the issue

**Comment by leandro-lucarella-sociomantic** [comment]
> The argument to -b is the upstream branch you want your changes pulled into, not your local branch.

Ohhhhh! My eyes are so used to read `-c` in that context that I was always reading `-c` where it said `-b` :)

**Comment by leandro-lucarella-sociomantic** [comment]
To name the branch in your fork you can use `-c`, that won't create a local branch but a branch in your GitHub fork. I guess that's what you wanted. If you want to use a local branch, just use it locally in git as usual and git-hub will use that branch name to create the branch in your fork too to crfeate the PR.
