### ISSUE TITLE
Python 3 issue that isn't handled by 2to3: type of `stderr`

### ISSUE THREAD

**Issue by jean** [sociomantic-tsunami/git-hub#221]
I got this:

```
$ ./generate-bash-completion
Traceback (most recent call last):
  File "git-hub", line 2156, in <module>
    main()
  File "git-hub", line 2121, in main
    config = Config()
  File "git-hub", line 316, in __init__
    self.username = git_config('username', getpass.getuser())
  File "git-hub", line 272, in git_config
    return git(*cmd)
  File "git-hub", line 218, in git
    raise GitError(proc.returncode, args, stderr.rstrip('\n'))
TypeError: a bytes-like object is required, not 'str'
```

At that point, `stderr` is `b''`.

To fix it, I could do this:

```
@@ -215,7 +215,7 @@ def git(*args, **kwargs):
     proc = subprocess.Popen(args, **kwargs)
     (stdout, stderr) = proc.communicate()
     if proc.returncode != 0:
-        raise GitError(proc.returncode, args, stderr.rstrip('\n'))
+        raise GitError(proc.returncode, args, str(stderr).rstrip('\n'))
     return stdout.rstrip('\n')
```

If my fix is correct, maybe worth adding to the README?

**Comment by leandro-lucarella-sociomantic** [comment]
String handling is a mess unfortunately. This really needs to use a lot of `from __future__ import ...` to be more python3 compatible. At this point I'm not sure if it's worth adding little hacks, but OTOH if this small fix makes it work for you with `2to3`, it can be applied, `str(stderr)` shouldn't change anything in py2.

**Comment by jean** [comment]
This one I "fixed" (avoided) by simply `%s/$PYTHON/python2` in the `Makefile` :grimacing: 
I agree that this is better addressed in a proper port.
