### ISSUE TITLE
Port to Python3

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/git-hub#224]
Python 2 will be retired in 2020. Yes, is still 2.5 years to go, but eventually this will have to happen.

As a start, we should use more and more `from __future__ import *` to have a gradual and painless migration.

This is a very good resource for this: http://python-future.org/

**Comment by leandro-lucarella-sociomantic** [comment]
Related issues:

* https://github.com/sociomantic-tsunami/git-hub/issues/46
* https://github.com/sociomantic-tsunami/git-hub/issues/223
* https://github.com/sociomantic-tsunami/git-hub/issues/221

**Comment by Mic92** [comment]
We probably going to remove it from nixpkgs at some point because of python2 dependency.

**Comment by joshtriplett** [comment]
This is now becoming an issue in Debian, as well.

**Comment by llucax** [comment]
Bumping priority to high. It shouldn't be hard to get this done, I'll try to allocate some time to do it.

**Comment by bokchan** [comment]
Tried porting using 2to3, (https://docs.python.org/3.7/library/2to3.html). 
Fixes the imports for python 3

Wrt adapting the `Makefile`, would a change as below be sufficient/sensible 

```python
export PYTHON ?= python3
...
	sed -i 's|^#!/usr/bin/env python3$$|#!/usr/bin/env $(PYTHON)|' \
			$(DESTDIR)$(prefix)/bin/git-hub
```   

Do we wanna go full python 3 and add type annotations as well?

**Comment by llucax** [comment]
> Tried porting using 2to3, (https://docs.python.org/3.7/library/2to3.html).
> Fixes the imports for python 3

Cool, thanks!

> Do we wanna go full python 3 and add type annotations as well?

In my experience type annotations in Python 3 are still a bit in the early stages and not all libraries implement them. Also, for small script like this they don't provide so much, usually larger codebases benefit more from static typing. Because of this I have almost zero personal interest in adding annotations, but I'd be happy to merge a good PR adding them **iff** it also adds a type checker (like http://mypy-lang.org/) to the CI, so we make sure those type annotations are actually used for something, as the Python interpreter just ignores them for now.

**Comment by bokchan** [comment]
Comment from git-hub with unicode chars ★ ☹  ⚓

**Comment by Mic92** [comment]
Your script 

> > Tried porting using 2to3, ([docs.python.org/3.7/library/2to3.html](https://docs.python.org/3.7/library/2to3.html)).
> > Fixes the imports for python 3
> 
> Cool, thanks!
> 
> > Do we wanna go full python 3 and add type annotations as well?
> 
> In my experience type annotations in Python 3 are still a bit in the early stages and not all libraries implement them. Also, for small script like this they don't provide so much, usually larger codebases benefit more from static typing. Because of this I have almost zero personal interest in adding annotations, but I'd be happy to merge a good PR adding them **iff** it also adds a type checker (like [http://mypy-lang.org](http://mypy-lang.org/)) to the CI, so we make sure those type annotations are actually used for something, as the Python interpreter just ignores them for now.

Your script seems to only use the stdlib, which is fully supported by typeshed. Which means you can get fully typechecking coverage. But even if you are missing out on some dependencies it is still a great help when refactoring internal code in my experience.

**Comment by bokchan** [comment]
Forgot to write a release note. But I assume this will be the main feature for v2.0.0 so might make sense to cook it up at the same time as the release.

**Comment by llucax** [comment]
No, I think it would be better to add it now as usual :)

**Comment by bokchan** [comment]
> No, I think it would be better to add it now as usual :)

Oki. I will create an MR for that

**Comment by llucax** [comment]
Done in #279.
