### ISSUE TITLE
issue update: option to edit only title

### ISSUE THREAD

**Issue by jwilk** [sociomantic-tsunami/git-hub#240]
I often want to update issue title, but leave the issue description intact.
At the moment, there's no good way to do this using git-hub:

* The `-m` option would require me to put the whole original description on the command line. This is completely impractical.

* The `-e` option kinda works, but I'm always anxious that it will mangle the description somehow, for example by stripping lines starting with <tt># </tt> that were present in the original description.

**Comment by leandro-lucarella-sociomantic** [comment]
Fixed by #250.
