### ISSUE TITLE
Draft PRs

### ISSUE THREAD

**Issue by nomeata** [sociomantic-tsunami/git-hub#260]
Github added a new feature: [Draft PRs](https://github.blog/2019-02-14-introducing-draft-pull-requests/). I guess a `git hub pull new --draft` option might make sense.

**Comment by leandro-lucarella-sociomantic** [comment]
This definitely looks like a great addition, and it should be fairly easy to implement.

**Comment by leandro-lucarella-sociomantic** [comment]
Moving to Future milestone because it is still experimental and we don't have an easy way to support experimental features (custom `Accept:` header) right now.

**Comment by Marenz** [comment]
I would like to suggest also a short-notation: `-d` ;)

**Comment by daniel-zullo** [comment]
Done in #269 and #275
