### ISSUE TITLE
`clean_message` mangles markdown

### ISSUE THREAD

**Issue by oxij** [sociomantic-tsunami/git-hub#261]
`# some text` signifies a header named "some text" in markdown. Meanwhile, `clean_message` function removes all of those lines.

**Comment by jwilk** [comment]
See also #187.

**Comment by oxij** [comment]
A bit of context: I tried to pipe an output of a script to `git-hub pull new` and the result seen on GitHub confused me. So, working from the principle of least confusion I'd say something else should be used to start a comment line. For instance, #262.

**Comment by leandro-lucarella-sociomantic** [comment]
It can be argued that having `#` as a comment marker on a `git` editor is also the least surprise, but I could understand there is less risk with that.

**Comment by daniel-zullo** [comment]
Closed by #262
