### ISSUE TITLE
Please look for and use pull request templates

### ISSUE THREAD

**Issue by joshtriplett** [sociomantic-tsunami/git-hub#273]
github supports pull request templates, which many projects use to encourage the inclusion of specific information in pull requests. github looks for them in a few different locations, and other tools look for them in a few other locations; when found, the pull request form will use them as the initial contents of the PR's comment box. However, `git hub pull new` does not do so, which can lead to unintentionally ignoring a project's conventions..

I would suggest the following, which should be relatively simple:

- Look for `pull_request_template.md` or `pull_request_template.txt` (both case-insensitive), in the root of the repository, the `docs/` directory, or the `.github/` directory.
- If found, then when constructing the initial contents of the editor to write the pull request, insert the template between the currently computed subject and body (subject, blank line, template, blank line, body)

Thank you for git-hub; I find it incredibly useful and a huge boost to my productivity.

**Comment by daniel-zullo** [comment]
I'll take over #262 as this requirement depends on it.

**Comment by llucax** [comment]
This was done in #274.
