### ISSUE TITLE
Please enable remote.fork.prune by default

### ISSUE THREAD

**Issue by joshtriplett** [sociomantic-tsunami/git-hub#291]
When cloning in the default triangular mode, the user owns the `fork` remote.  I'd love to have `remote.fork.prune` set to true in the freshly cloned repository's git configuration by default. That would mean that `git remote update` will automatically prune branches from the `fork` remote that have been remotely deleted (e.g. from hitting the "delete branch" button on a merged PR).

**Comment by llucax** [comment]
Hi josh! Even when I also usually like to prune remotes on update/fetch, I'm not sure the tool should be calling the shots for the user here, specially when there are easy ways to set this by default globally (with `git config --global remote.fork.prune true` or even for all remotes with `git config --global fetch.prune true`.

If you could give some extra reasons why you think the tool should be making these kind of decisions for the user, I would love to hear them. Thanks!

**Comment by joshtriplett** [comment]
On Mon, Dec 28, 2020 at 12:46:28PM -0800, Leandro Lucarella wrote:
> Hi josh! Even when I also usually like to prune remotes on update/fetch, I'm not sure the tool should be calling the shots for the user here, specially when there are easy ways to set this by default globally (with `git config --global remote.fork.prune true` or even for all remotes with `git config --global fetch.prune true`.
> 
> If you could give some extra reasons why you think the tool should be making these kind of decisions for the user, I would love to hear them. Thanks!

The user may not necessarily want to enable pruning globally, because
they may want to preserve information that a remote they don't control
removed. But for a remote they *do* control, where GitHub offers
one-click buttons to remove merged PR branches, it makes sense to keep
the `fork` remote's heads in sync.

I also don't think a global `remote.fork.prune` makes sense, because the
remote name `fork` may not have the same meaning in every repository
(though it *probably* does). But git-hub knows, when setting up a
repository, that it's creating a remote to correspond to the user's
fork; it has more precise information than the global git configuration
does.

Based on that, I think it makes sense to set the default.

Regardless of the default, though, I'd love to have the *option* to
enable this.

**Comment by llucax** [comment]
Hi Josh. Thanks for clarifying further. One thing that I was not seeing is how the fork differentiates from upstream in regards of pruning, and now I see what you mean by *control*. However, in my experience, controlling your fork, at least in terms of branches that are removed, is not always that straightforward. If you fork a private repo, the owner of the private repo can still remove branches in the fork, and at least in my experience it was a common practice to delete branches from other people's forks when merging a PR (as a *favour* to the person sending the PR, as the convention was that branches used in PRs are only short-lived and used for that PR).

This is why I still don't see it so black and white, and when talking about performing actions that could potentially mean data loss (granted, with git is difficult but still if someone removes a branch and an automated git gc is invoked, it could happen), I'm inclined to go with the safe bet and let the user do that sort of configuration manually.

That said, if there is any way to make your workflow easier that doesn't mean pruning remotes by default without the user asking explicitly for it, I'm very willing to add it.

I guess if we add a `clone` option plus a `git config hub.prunefork` option that you can set globally to make it your own default it could work. Then you only have to configure this behavior once globally and then all `git hub clone` will configure the cloned repo as you want.

A more generic approach would be to have an arbitrary script run on clone, specified by `git config hub.clonescript` (and defaulting to none). I guess this could let users override other git configuration only when cloning via `git hub`. In your case it should suffice to do `git config --global hub.clonescript "git config remote.fork.prune true"`.

Feedback is appreciated!

**Comment by Geod24** [comment]
> but still if someone removes a branch and an automated git gc is invoked, it could happen

Actually not, it takes 30 days before anything is collected.
While I understand the theoretical argument, the practice I witnessed has been overwhelmingly in favor of prune.

**Comment by joshtriplett** [comment]
git-gub can know if it's cloning a public or private repo, right? Could the default for public repos be to prune?

**Comment by llucax** [comment]
> Actually not, it takes 30 days before anything is collected.

This is, of course, also configurable, so I don't dare this will be always the case.

>  While I understand the theoretical argument, the practice I witnessed has been overwhelmingly in favor of prune.

As I said, me too, and use it regularly. And for people like you and me, there is `git config --global fetch.prune true` (or the more conservative option using `remote.fork.prune`).

But my point still is, I don't want to diverge from git defaults because of *principle of least surprise* (and again, specially when talking about removing stuff). If git doesn't think it is a good default, then I'm very cautious to go against that. Also this tool always tried to be as close as possible to git behavior.

The above also goes for:
> git-gub can know if it's cloning a public or private repo, right? Could the default for public repos be to prune?

Yes, it is technically possible, but I don't like the tool getting that smart, behaving differently if a repo is public or private. This at least would surprise me. And again, specially when we are talking about saving one single command each time you clone a repo (and this only if you don't want to set the default globally in git). I'm having a lot of trouble seeing a justification in it, adding more surprise factor, possibility of data loss (even if the cases would be extremely rare), etc. when the alternative is almost effortless.

All that said, I'm still willing to add a way to improve this particular workflow, as long as it's not the default.

**Comment by joshtriplett** [comment]
On Tue, Dec 29, 2020 at 01:49:44PM -0800, Leandro Lucarella wrote:
> > git-gub can know if it's cloning a public or private repo, right? Could the default for public repos be to prune?
> 
> Yes, it is technically possible, but I don't like the tool getting that smart, behaving differently if a repo is public or private. This at least would surprise me. And again, specially when we are talking about saving one single command each time you clone a repo (and this only if you don't want to set the default globally in git). I'm having a lot of trouble seeing a justification in it, adding more surprise factor, possibility of data loss (even if the cases would be extremely rare), etc. when the alternative is almost effortless.
> 
> All that said, I'm still willing to add a way to improve this particular workflow, as long as it's not the default.

I'd be happy with an option to enable this for the fork remote when
cloning a repository in triangular mode. It'd be more convenient as the
default, but if I need to set an option once in git-hub's configuration,
that's still much easier than setting an option in every repository's
configuration.

A quick check currently turns up at least 62 repositories on my system
cloned with git-hub.

**Comment by llucax** [comment]
OK, then I will go with the more generic solution of adding a clone script and adding this use case as an example in the docs. I'll try to sneak it in v2.1.0.

**Comment by llucax** [comment]
Please have a look at (and ideally try out) #292.

**Comment by llucax** [comment]
Since there was a lack of response on the suggested solution I will assume it's good enough to close this issue.
