### ISSUE TITLE
CI: git describe is not getting the tag being created in the create event

### ISSUE THREAD

**Issue by llucax** [sociomantic-tsunami/git-hub#302]
In #301 we migrated to GitHub Actions, and we are creating and archiving the Debian package as an artifact, but `git` is not getting the latest tag when doing a `describe`. I'm not sure if the `checkout` step is not fetching the latest tag for some reason or what else is going on.

Re-running the job doesn't fix anything so it doesn't seem to be a timing issue and it's very weird because it does find the previous tag, so it is also fetching tags.

**Comment by jwilk** [comment]
The checkout step is doing something weird:

```
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules origin +3c73ead8f28f635d1b59154462f284be536e95b5:refs/tags/v2.1.2
/usr/bin/git checkout --progress --force refs/tags/v2.1.2
```

If I do the above, I also get:
```console
$ git describe
v2.1.1-8-g3c73ead
```

**Comment by jwilk** [comment]
I think this is https://github.com/actions/checkout/issues/649 ("Signed tags incorrectly checked out").

As a work-around, you could pass `--tags` to `git describe`.

**Comment by llucax** [comment]
Oh, damn you GitHub! Thanks for looking into this. We wanted to explicitly use annotated tags to make sure describe is only done on those and not the lightweight ones. I think for now we can just live with this until it is properly fixed.

**Comment by jwilk** [comment]
I guess you could re-fetch the tags from GitHub:
```console
$ git fetch origin --tags -f
From https://github.com/sociomantic-tsunami/git-hub
 t [tag update]      v2.1.2     -> v2.1.2
$ git describe
v2.1.2
```

**Comment by llucax** [comment]
Yeah, I think this is the most sensible workaround. Maybe even just fetching `GITHUB_REF` explicitly if only the current tag is missing.
