### ISSUE TITLE
Check the tracking branch points to the upstream repo when using it as the base branch for new pull requests

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic-tsunami/git-hub#92]
Should check that the (supposedly) desired upstream really exists before creating the PR or it would fail with a cryptic error for the user when it doesn't exist.

**Comment by llucax** [comment]
This was also reported in the Debian issue tracker: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=807862
